### ISSUE TITLE
Only .marksman.toml exists, this plugin will be enabled

### ISSUE THREAD

**Issue by Freed-Wu** [yaegassy/coc-marksman#1]
According to [marksman](https://github.com/artempyanykh/marksman):

> check your project into version control, or create a .marksman.toml at the root folder of your project

However, this plugin cannot detect .git, only detect .marksman.toml. Is it a bug?

Thanks.

**Comment by yaegassy** [comment]
The same startup conditions apply to VSCode extension. <https://github.com/artempyanykh/marksman-vscode>

**Comment by yaegassy** [comment]
I found that some other LSP clients do indeed have a plugin that starts `.git` as the root directory.

Check the behavior and consider adjusting coc-marksman.

**Comment by Freed-Wu** [comment]
Looks like <https://github.com/yaegassy/coc-marksman/commit/e7e04d541b1ad9e8c2a7008e03816072eccd118b> fix this issue.

**Comment by yaegassy** [comment]
It seems to work fine, so I adjusted it.  Please update `coc-marksman`. `:CocUpdate`.

Thanks for the info. 🙇

**Comment by Freed-Wu** [comment]
I have tested it can work. Great! :+1:
