### ISSUE TITLE
How to create TOC

### ISSUE THREAD

**Issue by AlexRainHao** [yaegassy/coc-marksman#2]
I noticed https://github.com/artempyanykh/marksman/pull/17 brought the feature of creating table of content, or TOC.
But I have no idea how to use `coc-marksman` to create it.

**Comment by yaegassy** [comment]
Upon investigation, it seems that this CodeAction can be displayed by mapping `<Plug>(coc-codeaction-source)` and executing it in coc.nvim. Please refer to the README of coc.nvim for an example of setting up the mapping.

If you want to execute it directly from the ex command without mapping, it appears to be as follows.

```vim
:call CocActionAsync('codeAction', '', ['source'], v:true)
```

---

**DEMO**:

Action

<img width="489" alt="coc-marksman-2-1" src="https://user-images.githubusercontent.com/188642/232205558-4a5f98bc-a493-4999-99e0-943a62b64d5f.png">

Done

<img width="488" alt="coc-marksman-2-2" src="https://user-images.githubusercontent.com/188642/232205573-8108fdbd-a4db-42c1-bac0-3333aa10c1c4.png">

**Comment by yaegassy** [comment]
Upon investigation, it seems that this CodeAction can be displayed by mapping `<Plug>(coc-codeaction-source)` and executing it in coc.nvim. Please refer to the README of coc.nvim for an example of setting up the mapping.

If you want to execute it directly from the ex command without mapping, it appears to be as follows.

```vim
:call CocActionAsync('codeAction', '', ['source'], v:true)
```

---

**Action**:

<img width="489" alt="coc-marksman-2-1" src="https://user-images.githubusercontent.com/188642/232205626-34f6ef51-b607-4757-a1cc-2eb074cf676b.png">

**Done**:

<img width="488" alt="coc-marksman-2-2" src="https://user-images.githubusercontent.com/188642/232205632-1554805d-6da0-43a3-9aad-fbe3eee9a1a6.png">

**Comment by AlexRainHao** [comment]
Great! I tried it and succeeded, thanks for your working and reply
